In [ ]:
'''function to take three students names
 and marks using keyword arguments
 and print the name and marks of
the student with highest marks'''
def highest_marks(**students):
    highest_marks = 0
    highest_marks_student = None

    for name, marks in students.items():
        if marks > highest_marks:
            highest_marks = marks
            highest_marks_student = name

    print(f"Student with the highest marks is {highest_marks_student} with {highest_marks} marks.")
highest_marks(Student1=80, Student2=90, Student3=85)

Student with the highest marks is Student2 with 90 marks.

In [ ]:
#A function to return domain name from a website name

def get_domain_name(website_url):

    parts = website_url.split('.')

    domain_name = parts[-1]

    return domain_name

website_url = "https://www.example.com"
domain_name = get_domain_name(website_url)
print("Domain name:", domain_name)

Domain name: com

In [ ]:

'''program to take month and year
 and calculate age in years and
months up to march-2024'''
from datetime import datetime
def calculate_age(month, year):
    current_date = datetime.now()
    march_2024 = datetime(2024, 3, 1)
    dob = datetime(year, month, 1)
    age = march_2024 - dob
    age_years = age.days // 365
    age_months = (age.days % 365) // 30

    return age_years, age_months

month = int(input("Enter the birth month (1-12): "))
year = int(input("Enter the birth year: "))
age_years, age_months = calculate_age(month, year)
print(f"Age up to March 2024: {age_years} years and {age_months} months")

Enter the birth month (1-12): 2
Enter the birth year: 2003
Age up to March 2024: 21 years and 1 months

In [ ]:
#Write a function to take 4-bit binary number and check whether odd or even.
def is_even_or_odd(binary):
    decimal = int(binary, 2)
    if decimal % 2 == 0:
        return "Even"
    else:
        return "Odd"
binary_number = input("Enter a 4-bit binary number: ")
if len(binary_number) != 4 or not all(bit in '01' for bit in binary_number):
    print("Invalid input! Please enter a valid 4-bit binary number.")
else:
    result = is_even_or_odd(binary_number)
    print(f"The binary number {binary_number} is {result}.")

Enter a 4-bit binary number: 1010
The binary number 1010 is Even.

In [ ]:
#program to find difference between two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
difference2 = set1.difference(set2)
print("Difference :", difference2)

Difference : {1, 2, 3}

In [ ]:
import random

def roll_two_dice():
    dice1 = random.randint(1, 6)
    dice2 = random.randint(1, 6)

    print("First die:", dice1)
    print("Second die:", dice2)
    print("Sum of two dice:", dice1 + dice2
roll_two_dice()

First die: 6
Second die: 1
Sum of two dice: 7

In [1]:
# write a function to return average of a list.
def avg(nums):
    return sum(nums)/len(nums)
mylist = [92,91,71,52,81,72,55,67,76]
print('My_list:',mylist)
print('Averge of list:',avg(mylist))

My_list: [92, 91, 71, 52, 81, 72, 55, 67, 76]
Averge of list: 73.0

In [3]:
'''
Write a function to take sequence of number separated by comma and return list of numbers.
Eg: fun (“2,4,1,5,3”) returns list = [2,4,1,5,3]
'''
def num_list(string):
    nums = [int(i) for i in string.split(',')]
    return nums
string = input("Enter sequence of numbers separated by comma's:")
print('Numbers list:',num_list(string))

Enter sequence of numbers separated by comma's:23,45,1,7,89,90
Numbers list: [23, 45, 1, 7, 89, 90]

In [4]:
# Write a program to print all the permutation of using ‘a’, ‘b’, ‘c’.
permutations = []
for i in 'abc':
    for j in 'abc':
        for k in 'abc':
            permutations.append(i+j+k)
print("Permutations with repetation:",permutations)
print("Permuations wihtout repetation:", [i for i in permutations if 'a' in i and 'b' in i  and 'c' in i])

Permutations with repetation: ['aaa', 'aab', 'aac', 'aba', 'abb', 'abc', 'aca', 'acb', 'acc', 'baa', 'bab', 'bac', 'bba', 'bbb', 'bbc', 'bca', 'bcb', 'bcc', 'caa', 'cab', 'cac', 'cba', 'cbb', 'cbc', 'cca', 'ccb', 'ccc']
Permuations wihtout repetation: ['abc', 'acb', 'bac', 'bca', 'cab', 'cba']